name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run this action
        uses: ./
      - name: Check binaries
        run: |
          echo -n "architect: "
          architect version

          echo -n "semver: "
          semver --version
