name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Checkout code
        uses: actions/checkout@v2-beta
      - name: Lint
        run: "npm run lint"
      - name: Test this action
        uses: ./
